import { Issue } from '../../types/issue.types';

export const mockIssues: Issue[] = [
  {
    id: 444,
    node_id: 'string',
    url: 'string',
    repository_url: 'string',
    labels_url: 'string',
    comments_url: 'string',
    events_url: 'string',
    html_url: 'string',
    number: 9,
    state: 'string',
    title: 'my issue',
    body: 'string',
    user: {
      login: 'simpson',
      id: 3,
      node_id: 'string',
      avatar_url: 'string',
      gravatar_id: 'string',
      url: 'string',
      html_url: 'string',
      followers_url: 'string',
      following_url: 'string',
      gists_url: 'string',
      starred_url: 'string',
      subscriptions_url: 'string',
      organizations_url: 'string',
      repos_url: 'string',
      events_url: 'string',
      received_events_url: 'string',
      type: 'string',
      site_admin: true,
    },
    labels: [
      {
        id: 3,
        node_id: 'string',
        url: 'string',
        name: 'string',
        description: 'string',
        color: 'string',
        default: true,
      },
    ],
    assignee: {
      login: 'Simpson',
      id: 4,
      node_id: 'string',
      avatar_url: 'string',
      gravatar_id: 'string',
      url: 'string',
      html_url: 'string',
      followers_url: 'string',
      following_url: 'string',
      gists_url: 'string',
      starred_url: 'string',
      subscriptions_url: 'string',
      organizations_url: 'string',
      repos_url: 'string',
      events_url: 'string',
      received_events_url: 'string',
      type: 'string',
      site_admin: true,
    },
    assignees: [
      {
        login: 'Sssimpson',
        id: 4,
        node_id: 'string',
        avatar_url: 'string',
        gravatar_id: 'string',
        url: 'string',
        html_url: 'string',
        followers_url: 'string',
        following_url: 'string',
        gists_url: 'string',
        starred_url: 'string',
        subscriptions_url: 'string',
        organizations_url: 'string',
        repos_url: 'string',
        events_url: 'string',
        received_events_url: 'string',
        type: 'string',
        site_admin: true,
      },
    ],
    milestone: {
      url: 'string',
      html_url: 'string',
      labels_url: 'string',
      id: 9,
      node_id: 'string',
      number: 99,
      state: 'string',
      title: 'issssue',
      description: 'string',
      creator: {
        login: 'sssimps',
        id: 99,
        node_id: 'string',
        avatar_url: 'string',
        gravatar_id: 'string',
        url: 'string',
        html_url: 'string',
        followers_url: 'string',
        following_url: 'string',
        gists_url: 'string',
        starred_url: 'string',
        subscriptions_url: 'string',
        organizations_url: 'string',
        repos_url: 'string',
        events_url: 'string',
        received_events_url: 'string',
        type: 'string',
        site_admin: true,
      },
      open_issues: 9,
      closed_issues: 999,
      created_at: 'string',
      updated_at: 'string',
      closed_at: 'string',
      due_on: 'string',
    },
    locked: false,
    active_lock_reason: null,
    comments: 99,
    pull_request: {
      url: 'string',
      html_url: 'string',
      diff_url: 'string',
      patch_url: 'string',
    },
    closed_by: null,
    closed_at: null,
    created_at: 'string',
    updated_at: 'string',
    author_association: 'string',
    state_reason: 'string',
  },
];
